<thead>
    <tr>
        <td>
            Relation
        </td>
        <td>
            Name
        </td>
        <td>
            Timeframe
        </td>
        <td>
            Type
        </td>
        <td>
            Origin
        </td>
        <td>
            Distance
        </td>
    </tr>
</thead>
<tbody>
</tbody>
~                                  
